### PR TITLE
Added npm dependency of bem-core

### PR DESCRIPTION
**Pull request by remnev**

### CODE REVIEW

**Comment by remnev** [comment]
In addition to #56 
Bemhtml templates won't work without bem-core. Because we must ensure bem-core installation in case of using npm.

**Comment by remnev** [comment]
I added a note to the docs about bem-core dependency.

**Comment by tadatuta** [comment]
actually BEMHTML should work just fine without `bem-core` since `bem-xjst >= 2.x`

**Comment by zxqfox** [comment]
Yeah, I guess we should get rid of older bem-xjst versions. Time's come.

**Comment by tadatuta** [comment]
We dropped old bem-xjst everywhere, let's close the issue!

**Pull request closed without merging**
