### PR TITLE
Add nonce support for metrika

### PR DESCRIPTION
**Pull request by birhoff**

### CODE REVIEW

**Comment by tadatuta** [comment]
@birhoff please update tests

**Comment by remnev** [comment]
What's problem it solves?

**Comment by birhoff** [comment]
Add support for nonce token. It's need for CSP. https://w3c.github.io/webappsec-csp/#match-nonce-to-source-list

**Comment by remnev** [comment]
Ok, I got the reason. We need to do a bit more then you did: add the attribute to another blocks, cover it by tests, update examples in the docs. If you don't want to do it (or don't have enough time), I will do it myself later.

**Pull request closed without merging**
