### PR TITLE
Get rid of bem-core dependency

### PR DESCRIPTION
**Pull request by remnev**
Fixes gh-60

### CODE REVIEW

**Comment by tadatuta** [comment]
there's still https://github.com/bem-contrib/stat-counters/blob/master/common.blocks/google-analytics/google-analytics.browser.js so we should decide what to do with it

**Comment by remnev** [comment]
> there's still https://github.com/bem-contrib/stat-counters/blob/master/common.blocks/google-analytics/google-analytics.browser.js so we should decide what to do with it

I propose to don't care.

**Comment by tadatuta** [comment]
> I propose to don't care.

let's add some notes to readme at least?

**Comment by zxqfox** [comment]
Can we make 2 levels for bem-core and for vanilla js?

**Comment by tadatuta** [comment]
@zxqfox do we really need bem library with vanilla js? can't users of vanilla version use API without any additional library?

**Comment by remnev** [comment]
> let's add some notes to readme at least?

I've updated

**Pull request merged**
